src/Entity/Client.php
<?php

namespace App\Entity;

use DateTimeInterface;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToOne;
use Doctrine\ORM\Mapping\JoinColumn;


/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client extends User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $Pays;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Add1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Add2;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Permis;

    /**
     * @ORM\Column(type="date")
     */
    private $Date_Permis;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CIN;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $Date_CIN;

    /**
     * @ORM\Column(type="date")
     */
    private $Date_Naissance;

    /**
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="Client", fetch="LAZY")
     */
    private $Locations;

    /**
     * @ORM\OneToMany(targetEntity=Payment::class, mappedBy="Client", fetch="LAZY", orphanRemoval=true)
     */
    private $payments;

    /**
     * @ORM\OneToMany(targetEntity=Feedback::class, mappedBy="Client", fetch="LAZY")
     */
    private $feedback;


    public function __construct()
    {
        $this->Locations = new ArrayCollection();
        $this->payments = new ArrayCollection();
        $this->feedback = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(?string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function getAdd1(): ?string
    {
        return $this->Add1;
    }

    public function setAdd1(string $Add1): self
    {
        $this->Add1 = $Add1;

        return $this;
    }

    public function getAdd2(): ?string
    {
        return $this->Add2;
    }

    public function setAdd2(string $Add2): self
    {
        $this->Add2 = $Add2;

        return $this;
    }

    public function getPermis(): ?string
    {
        return $this->Permis;
    }

    public function setPermis(string $Permis): self
    {
        $this->Permis = $Permis;

        return $this;
    }

    public function getDate_Permis(): ?string
    {
        $newDate = $this->Date_Permis->format('d/m/Y');
        return $newDate;    
    }

    public function getDatePermis(): ?DateTimeInterface
    {
        return $this->Date_Permis;
    }

    public function setDatePermis(DateTimeInterface $dateTime): self
    {
        $this->Date_Permis = $dateTime;

        return $this;
    }

    public function getCIN(): ?string
    {
        return $this->CIN;
    }

    public function setCIN(string $CIN): self
    {
        $this->CIN = $CIN;

        return $this;
    }

    public function getDate_CIN(): ?string
    {
        $newDate = $this->Date_CIN->format('d/m/Y');
        return $newDate;    
    }

    public function getDateCIN(): ?DateTimeInterface
    {
        return $this->Date_CIN;
    }

    public function setDateCIN(?DateTimeInterface $dateTime): self
    {
        $this->Date_CIN = $dateTime;

        return $this;
    }

    public function getDate_Naissance(): ?string
    {
        $newDate = $this->Date_Naissance->format('d/m/Y');
        return $newDate;    
    }

    public function getDateNaissance(): ?DateTimeInterface
    {
        return $this->Date_Naissance;
    }

    public function setDateNaissance(DateTimeInterface $dateTime): self
    {
        $this->Date_Naissance = $dateTime;

        return $this;
    }

    /**
     * @return Collection<int, Location>
     */
    public function getLocations(): Collection
    {
        return $this->Locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->Locations->contains($location)) {
            $this->Locations[] = $location;
            $location->setClient($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->Locations->removeElement($location)) {
            // set the owning side to null (unless already changed)
            if ($location->getClient() === $this) {
                $location->setClient(null);
            }
        }

        return $this;
    }

    // public function getUser(): ?User
    // {
    //     return $this->User;
    // }

    // public function setUser(User $User): self
    // {
    //     $this->User = $User;

    //     return $this;
    // }

    public function __toString() : string {
        return $this->id;
    }

    /**
     * @return Collection<int, Payment>
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setClient($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->removeElement($payment)) {
            // set the owning side to null (unless already changed)
            if ($payment->getClient() === $this) {
                $payment->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Feedback>
     */
    public function getFeedback(): Collection
    {
        return $this->feedback;
    }

    public function addFeedback(Feedback $feedback): self
    {
        if (!$this->feedback->contains($feedback)) {
            $this->feedback[] = $feedback;
            $feedback->setClient($this);
        }

        return $this;
    }

    public function removeFeedback(Feedback $feedback): self
    {
        if ($this->feedback->removeElement($feedback)) {
            // set the owning side to null (unless already changed)
            if ($feedback->getClient() === $this) {
                $feedback->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Payment.php
<?php

namespace App\Entity;

use App\Repository\PaymentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PaymentRepository::class)
 */
class Payment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sessionId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdOn;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="payments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Client;

    /**
     * @ORM\ManyToOne(targetEntity=Location::class, inversedBy="payments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Location;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSessionId(): ?string
    {
        return $this->sessionId;
    }

    public function setSessionId(?string $sessionId): self
    {
        $this->sessionId = $sessionId;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getCreated_On(): ?string
    {
        $newDate = $this->createdOn->format('d/m/Y');

        return $newDate;
    }


    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->createdOn;
    }

    public function setCreatedOn(\DateTimeInterface $createdOn): self
    {
        $this->createdOn = $createdOn;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->Location;
    }

    public function setLocation(?Location $Location): self
    {
        $this->Location = $Location;

        return $this;
    }
}

src/Entity/Settings.php
<?php

namespace App\Entity;

use App\Repository\SettingsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=SettingsRepository::class)
 * @Vich\Uploadable
 */
class Settings
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Photo_Couverture;

    /**
     *
     * @Vich\UploadableField(mapping="Settings_image", fileNameProperty="Photo_Couverture")
     * 
     * @var File|null
     */
    private ?File $Couverture = null;


    /**
     * @ORM\Column(type="string", length=501)
     */
    private $Propos;

    /**
     * @ORM\Column(type="string", length=501)
     */
    private $Ad;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Banner = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhotoCouverture(): ?string
    {
        return $this->Photo_Couverture;
    }

    public function setPhotoCouverture(string $Photo_Couverture): self
    {
        $this->Photo_Couverture = $Photo_Couverture;

        return $this;
    }

    public function getPropos(): ?string
    {
        return $this->Propos;
    }

    public function setPropos(string $Propos): self
    {
        $this->Propos = $Propos;

        return $this;
    }

    public function getAd(): ?string
    {
        return $this->Ad;
    }

    public function setAd(string $Ad): self
    {
        $this->Ad = $Ad;

        return $this;
    }

    public function getBanner(): ?bool
    {
        return $this->Banner;
    }

    public function setBanner(bool $Banner): self
    {
        $this->Banner = $Banner;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getCouverture(): ?File
    {
        return $this->Couverture;
    }

    public function setCouverture(?File $reel): void
    {
        $this->Couverture = $reel;

        if ($reel instanceof UploadedFile) {
            $this->updatedAt = new \DateTime();
        }
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToOne;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"user" = "User", "client" = "Client"})
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    protected $discr = 'user';
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    protected $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $Lastname;

    /**
     * @ORM\Column(type="json")
     */
    protected array $roles = [];

    /**
     * @OneToOne(targetEntity="Client")
     * @JoinColumn(name="client_id", referencedColumnName="id")
     */
    protected $client;

    /**
     * @ORM\Column(type="string")
     */
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->Email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->Email;
    }

    /**
    * @see UserInterface
    */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        $rls = [];
        foreach($roles as $role){
            $rls[$role] = $role;
        }
        return $rls;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /*public function __toString()
    {
        return $this->Email;
    }*/
}

templates/frontoffice/banner.html.twig
      <footer class="banner" style="padding:20px;">
         <div class="container">
            <div class="row">
               <div class="col-lg-12 col-md-12">
                  <div class="footer-box mb-md-40">
                     <h6 class="text-custom-white fw-600" >{{ setting.ad|raw}}</h6>
                  </div>
               </div>
            </div>
         </div>
         <div class="copyright">
            <div class="container">
               <div class="row">
                  <div class="col-12">
                     <p class="text-custom-white">© MBM Lab - 2022 | All Right Reserved</p>
                  </div>
               </div>
            </div>
         </div>
      </footer>

templates/frontoffice/edit.html.twig
{% extends 'frontoffice/index.html.twig' %}
{% block content %}
      <!-- End Subheader --><!-- Start Blog -->
      <div class="subheader normal-bg section-padding">
         <div class="container">
            <div class="row">
               <div class="col-12">
                  <h1 class="text-custom-white">Profile</h1>
                  <ul class="custom-flex justify-content-center">
                     <li class="fw-500"><a href="/" class="text-custom-white">Acceuil</a></li>
                     <li class="active fw-500">Profile</li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
      <!-- End Subheader --><!-- Start Listing detail -->
      <section class="section-padding bg-light-white listing-details">
         <div class="container">
            <div class="row">
               <div class="col-12">
                  <div class="listing-details-inner  bg-custom-white padding-20">
                     <div class="row">
                        <div class="col-lg-8">
                           <div class="row">
                              <div class="col-12">
                                 <div class="blog-details bg-custom-white">
                                    <hr>
                                    <!-- tags & social -->
                                    
                                    <!-- tags & social --><!-- post author -->
                                    <div class="bg-light-white padding-15 mb-xl-20">
                                       <div class="author-caption">
                                       {{ form_start(form) }}
                                          <div class="row">
                                             <div class="col-12">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">E-mail</label>
                                                   {{ form_widget(form.email, {'attr':{'class':'form-control form-control-custom',}}) }}                                                 
                                                </div>
                                             </div>
                                          </div>
                                                
                                          <div class="row">
                                             <div class="col-6">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Nom</label>
                                                   {{ form_widget(form.name, {'attr':{'class':'form-control form-control-custom'}}) }}                                                 
                                                </div>
                                             </div>
                                             <div class="col-6">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Prénom</label>
                                                   {{ form_widget(form.lastname, {'attr':{'class':'form-control form-control-custom'}}) }}                                                 
                                                </div>
                                             </div>
                                          </div>
                                          <div class="row">
                                             <div class="col-12">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Naissance</label>
                                                   {{ form_widget(form.Date_Naissance, {'attr':{'class':'form-control form-control-custom'}}) }} 
                                                </div>
                                             </div>
                                             </div>
                                          <div class="row">
                                             <div class="col-6">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Pays</label>
                                                   {{ form_widget(form.Pays, {'attr':{'class':'form-control form-control-custom','require' : "true"}}) }}                                                 
                                                </div>
                                             </div>
                                             <div class="col-6">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Telephone</label>
                                                   {{ form_widget(form.Telephone, {'attr':{'class':'form-control form-control-custom'}}) }}                                                 
                                                </div>
                                             </div>
                                          </div>
                                          
                                          
                                          <div class="row">
                                             <div class="col-6">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Addresse 1</label>
                                                   {{ form_widget(form.Add1, {'attr':{'class':'form-control form-control-custom',  'require' : "true"}}) }}                                                 
                                                </div>
                                             </div>
                                             <div class="col-6">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Addresse 2</label>
                                                   {{ form_widget(form.Add2, {'attr':{'class':'form-control form-control-custom'  }}) }} 
                                                </div>
                                             </div>
                                          </div>
                                          
                                          <div class="row">
                                             <div class="col-8">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Permis</label>
                                                   {{ form_widget(form.Permis, {'attr':{'class':'form-control form-control-custom'}}) }}                                                 
                                                </div>
                                             </div>
                                             <div class="col-4">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Date Livraison</label>
                                                   {{ form_widget(form.Date_Permis, {'attr':{'class':'form-control form-control-custom'}}) }}                                                 
                                                </div>
                                             </div>
                                          </div>

                                          <div class="row">
                                             <div class="col-8">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">CIN</label>
                                                   {{ form_widget(form.CIN, {'attr':{'class':'form-control form-control-custom', }}) }}                                                 
                                                </div>
                                             </div>
                                             <div class="col-4">
                                                <div class="form-group">
                                                   <label class="text-custom-black fw-500 fs-14">Date Livraison</label>
                                                   {{ form_widget(form.Date_CIN, {'attr':{'class':'form-control form-control-custom'}}) }}                                                 
                                                </div>
                                             </div>
                                          </div>
                                          
                                          
                                          {{ form_rest(form) }}
                                          </br>
                                          <div class="row">
                                             <button type="submit" class="btn-first btn-submit full-width btn-height">Modifier</button>
                                          </div>
                                       {{ form_end(form) }}
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <div class="col-lg-4">
                           <div class="row">
                              <div class="col-12">
                                 <div class="quick-quote bx-wrapper padding-20 mb-xl-30">
                                    <h5 class="text-custom-black">Reservations</h5>
                                    {% for reservation in app.user.locations %}
                                          <hr>
                                          <p class="fw-600"><a href="{{path('front_office_reservation',{'Num' : reservation.Num}) }}" class="text-custom-black"><b>{{ reservation.Vehicule.Marque }} : {{ reservation.Vehicule.Modele }}</b> du {{reservation.Date_Loc }} jusqu'à {{reservation.Date_Retour }}<a></p>
                                    {% endfor %}
                                    
                                 </div>
                                 <div class="quick-quote bx-wrapper padding-20 mb-xl-30">
                                    <h5 class="text-custom-black">Paiements</h5>
                                    {% for payment in app.user.payments %}
                                          <hr>
                                          <p class="fw-600"><a href="{{path('front_office_reservation',{'Num' : payment.location.Num}) }}" class="text-custom-black"><b>{{ payment.location.Vehicule.Marque }} : {{ payment.location.Vehicule.Modele }}</b> du {{payment.location.Date_Loc }} jusqu'à {{payment.location.Date_Retour }}<a></p>
                                          <p class="fw-600"><a href="#" class="text-custom-black"><b>ID</b> : {{ payment.sessionId }}</a></p>
                                          <p class="fw-600"><a href="#" class="text-custom-black"><b>Montant</b> : {{ payment.total }} DT </a><small style="float : right">{{ payment.created_On }}</br>{{ payment.status }}</small></p>
                                    {% endfor %}
                                    
                                 </div>
                                 <div class="need-help bx-wrapper padding-20">
                                    <h5 class="text-custom-black">Besoin d'aide ?</h5>
                                    <p class="text-light-dark">Nous serions plus qu'heureux de vous aider. Notre équipe de conseillers est à votre service 24h/24 et 7j/7 pour vous aider.</p>
                                    <ul class="custom">
                                       <li class="text-custom-blue fs-18"> <i class="fas fa-phone-alt"></i> <a href="#" class="text-light-dark">(+216) {{ setting.Tel }}</a> </li>
                                       <li class="text-custom-blue fs-18"> <i class="fas fa-envelope"></i> <a href="#" class="text-light-dark fs-14">{{ setting.Email }}</a> </li>
                                    </ul>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <!-- End Listing detail -->
      {% endblock %}